
CREATE PROCEDURE INSERT_INVENTORY
	-- Add the parameters for the stored procedure here
	@DATE DATE,
	@CATEGORY VARCHAR(50), 
	@BARCODE VARCHAR(50) ,
	@NAME VARCHAR(500), 
	@QUANTITY DECIMAL(18,2) ,
	@RE_ORDER DECIMAL(18,2),
	@SALE_QTY DECIMAL(18,2),
	@COST DECIMAL(18,2),
	@PRICE DECIMAL(18,2),
	@MARGIN DECIMAL(18,2),
	@VENDOR_CODE VARCHAR(100),
	@SKU VARCHAR(70),
	@PRODUCT_STATUS INT
AS
BEGIN

	INSERT INTO INVENTORY(DATE,CATEGORY,BARCODE,NAME,QUANTITY,RE_ORDER,SALE_QTY,COST,PRICE,MARGIN,VENDOR_CODE,SKU,PRODUCT_STATUS) VALUES(@DATE,@CATEGORY,@BARCODE,@NAME,@QUANTITY,@RE_ORDER,@SALE_QTY,@COST,@PRICE,@MARGIN,@VENDOR_CODE,@SKU,@PRODUCT_STATUS)

	
END
GO

CREATE PROCEDURE UPDATE_INVENTORY
	@ID INT ,
	@CATEGORY VARCHAR(50), 
	@BARCODE VARCHAR(50) ,
	@NAME VARCHAR(500), 
	@QUANTITY DECIMAL(18,2) ,
	@RE_ORDER DECIMAL(18,2),
	@SALE_QTY DECIMAL(18,2),
	@COST DECIMAL(18,2),
	@PRICE DECIMAL(18,2),
	@MARGIN DECIMAL(18,2),
	@VENDOR_CODE VARCHAR(100),
	@SKU VARCHAR(70)	
AS 
BEGIN
	UPDATE INVENTORY SET CATEGORY=@CATEGORY,BARCODE=@BARCODE,NAME=@NAME,QUANTITY=@QUANTITY,RE_ORDER=@RE_ORDER,SALE_QTY=@SALE_QTY,COST=@COST,PRICE=@PRICE,MARGIN=@MARGIN,VENDOR_CODE=@VENDOR_CODE,SKU=@SKU WHERE ID=@ID
END
GO

CREATE PROCEDURE UPDATE_INVENTORY_PRICE
	@BARCODE VARCHAR(50) ,
	@QUANTITY DECIMAL(18,2) ,
	@PRICE DECIMAL(18,2),
	@MARGIN DECIMAL(18,2)
AS 
BEGIN
	UPDATE INVENTORY SET QUANTITY=@QUANTITY,PRICE=@PRICE,MARGIN=@MARGIN WHERE BARCODE=@BARCODE
END
GO

CREATE PROCEDURE INSERT_CATEGORY
	@CATEGORY VARCHAR(50),
	@NOTES VARCHAR(1000)
AS 
BEGIN
	INSERT INTO CATEGORY(CATEGORY,NOTES) VALUES(@CATEGORY,@NOTES)
END
GO

CREATE PROCEDURE UPDATE_CATEGORY
	@ID INT,
	@CATEGORY VARCHAR(50),
	@NOTES VARCHAR(1000)
AS 
BEGIN
	UPDATE CATEGORY SET CATEGORY=@CATEGORY,NOTES=@NOTES WHERE ID=@ID
END
GO

CREATE PROCEDURE INSERT_USERS
	@NAME VARCHAR(255),
	@ID_NO VARCHAR(15),
	@ADDRESS VARCHAR(1000),
	@GENDER VARCHAR(50),
	@AGE INT,
	@CONTACT VARCHAR(100),
	@USERNAME VARCHAR(500),
	@PASSWORD VARCHAR(500)
AS 
BEGIN
	INSERT INTO USERS(NAME,ID_NO,ADDRESS,GENDER,AGE,CONTACT,USERNAME,PASSWORD) VALUES(@NAME,@ID_NO,@ADDRESS,@GENDER,@AGE,@CONTACT,@USERNAME,@PASSWORD)
END
GO

CREATE PROCEDURE UPDATE_USERS
	@ID INT,
	@NAME VARCHAR(255),
	@ID_NO VARCHAR(15),
	@ADDRESS VARCHAR(1000),
	@GENDER VARCHAR(50),
	@AGE INT,
	@CONTACT VARCHAR(100),
	@USERNAME VARCHAR(500),
	@PASSWORD VARCHAR(500)
AS 
BEGIN
	UPDATE USERS SET NAME=@NAME,ID_NO=@ID_NO,ADDRESS=@ADDRESS,GENDER=@GENDER,AGE=@AGE,CONTACT=@CONTACT,USERNAME=@USERNAME,PASSWORD=@PASSWORD WHERE ID=@ID
END
GO