CREATE VIEW SALES_REPORT 
AS 
SELECT        dbo.SALES.ID, dbo.INVENTORY.NAME, dbo.SALES.TRANS_DATE, dbo.SALES.BARCODE, dbo.SALES.QUANTITY, dbo.SALES.AMOUNT, dbo.SALES.PROFIT, dbo.SALES.SALE_TYPE
FROM            dbo.INVENTORY INNER JOIN
                         dbo.SALES ON dbo.INVENTORY.BARCODE = dbo.SALES.BARCODE;
GO
CREATE VIEW SHEDULED_REPORT 
AS
SELECT        dbo.SALES.ID, dbo.INVENTORY.NAME, dbo.SALES.TRANS_DATE, dbo.SALES.BARCODE, dbo.SALES.QUANTITY, dbo.SALES.AMOUNT, dbo.SALES.PROFIT, dbo.SALES.SALE_TYPE
FROM            dbo.INVENTORY INNER JOIN
                         dbo.SALES ON dbo.INVENTORY.BARCODE = dbo.SALES.BARCODE;
GO

